from nupe.core.serializers.person import PersonCreateSerializer, PersonDetailSerializer, PersonListSerializer
from nupe.core.serializers.student import StudentCreateSerializer, StudentDetailSerializer, StudentListSerializer
