from nupe.core.serializers.Person import PersonCreateSerializer, PersonDetailSerializer, PersonListSerializer
from nupe.core.serializers.Student import StudentCreateSerializer, StudentDetailSerializer, StudentListSerializer
