version: "3.8"

services:
    db:
        container_name: db
        image: postgres:13.0-alpine
        environment:
            # em caso de alteração, deve ser atualizado as variáveis da imagem docker do backend
            POSTGRES_USER: nupe
            POSTGRES_PASSWORD: nupe
            POSTGRES_DB: nupe
        volumes:
            - db:/var/lib/postgresql/data
        ports: 
            - "8865:5432"
        restart: always

volumes:
    db:

