from nupe.tests.integration_tests.endpoints.custom_handler_404 import CustomHandler404APITestCase
from nupe.tests.integration_tests.endpoints.image_upload import ProfileImageAPITestCase
from nupe.tests.integration_tests.endpoints.institution import CampusAPITestCase, InstitutionAPITestCase
from nupe.tests.integration_tests.endpoints.oauth2 import Oauth2APITestCase
from nupe.tests.integration_tests.endpoints.person import PersonAPITestCase
from nupe.tests.integration_tests.endpoints.student import StudentAPITestCase
from nupe.tests.integration_tests.endpoints.user import UserAPITestCase
