# Generated by Django 3.0.6 on 2020-06-22 21:25

from django.db import migrations, models

import nupe.file.models.image_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to=nupe.file.models.image_upload.make_path_profile_image)),
            ],
            options={"abstract": False,},
        ),
    ]
