# Generated by Django 3.1 on 2020-09-09 18:33

import secrets

from django.db import migrations, models

import nupe.file.models.image_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attachment_id",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=255,
                        unique=True,
                        help_text="Esse atributo é usado para fazer associação com outro objeto",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=255,
                        unique=True,
                        help_text="Esse atributo é usado para compor a url de acesso",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to=nupe.file.models.image_upload.make_path_image)),
            ],
            options={"abstract": False,},
        ),
    ]
