# Generated by Django 3.0.6 on 2020-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_add__image_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImageTest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="tests")),
            ],
            options={"abstract": False,},
        ),
    ]
