# Generated by Django 5.0.7 on 2024-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_add__profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
