# Generated by Django 3.0.5 on 2020-04-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "base_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.Base",
                    ),
                ),
            ],
            bases=("core.base",),
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "base_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.Base",
                    ),
                ),
            ],
            bases=("core.base",),
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="localizacoes",
                        related_query_name="localizacao",
                        to="core.Cidade",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="localizacoes",
                        related_query_name="localizacao",
                        to="core.Estado",
                    ),
                ),
            ],
            options={"unique_together": {("cidade", "estado")},},
        ),
        migrations.AddField(
            model_name="estado",
            name="cidades",
            field=models.ManyToManyField(
                related_name="estados", related_query_name="estado", through="core.Localizacao", to="core.Cidade"
            ),
        ),
    ]
