# Generated by Django 3.0.5 on 2020-04-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"verbose_name_plural": "Cities",},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        related_query_name="location",
                        to="core.City",
                    ),
                ),
            ],
            options={"verbose_name": "Location", "verbose_name_plural": "Locations",},
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "cities",
                    models.ManyToManyField(
                        related_name="states", related_query_name="state", through="core.Location", to="core.City"
                    ),
                ),
            ],
            options={"verbose_name_plural": "States",},
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                related_query_name="location",
                to="core.State",
            ),
        ),
        migrations.AlterUniqueTogether(name="location", unique_together={("city", "state")},),
    ]
