# Generated by Django 3.0.5 on 2020-05-14 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_add__city__state__location"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEducation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="grades",
                        related_query_name="grade",
                        through="core.AcademicEducation",
                        to="core.Course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="academiceducation",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academics_educations",
                related_query_name="academic_education",
                to="core.Course",
            ),
        ),
        migrations.AddField(
            model_name="academiceducation",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academics_educations",
                related_query_name="academic_education",
                to="core.Grade",
            ),
        ),
        migrations.AlterUniqueTogether(name="academiceducation", unique_together={("grade", "course")},),
    ]
