# Generated by Django 3.0.5 on 2020-04-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_city_state_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('courses', models.ManyToManyField(related_name='grades', related_query_name='grade', through='core.AcademicEducation', to='core.Course', verbose_name='cursos')),
            ],
            options={
                'verbose_name': 'Grau',
                'verbose_name_plural': 'Graus',
            },
        ),
        migrations.AddField(
            model_name='academiceducation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_educations', related_query_name='academic_education', to='core.Course', verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='academiceducation',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_educations', related_query_name='academic_education', to='core.Grade', verbose_name='grau'),
        ),
        migrations.AlterUniqueTogether(
            name='academiceducation',
            unique_together={('grade', 'course')},
        ),
    ]
