# Generated by Django 2.2.16 on 2020-10-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_add__city__state__location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True,),),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("address", models.CharField(max_length=75)),
                ("number", models.CharField(max_length=10)),
                ("website", models.CharField(max_length=50, null=True, blank=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("location", models.ForeignKey(on_delete=models.PROTECT, related_name="campus", to="core.Location",),),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="campus", to="core.Institution",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
