# Generated by Django 3.0.5 on 2020-04-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_course_grade_academic_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEducationCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "academic_education",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_campus",
                        to="core.AcademicEducation",
                        verbose_name="formação acadêmica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formação Acadêmica - Campus",
                "verbose_name_plural": "Formações Acadêmica do Campus",
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="nome")),
                (
                    "academic_education",
                    models.ManyToManyField(
                        related_name="campus",
                        through="core.AcademicEducationCampus",
                        to="core.AcademicEducation",
                        verbose_name="formação acadêmica",
                    ),
                ),
            ],
            options={"verbose_name": "Campus", "verbose_name_plural": "Campus",},
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="nome")),
            ],
            options={"verbose_name": "Instituição", "verbose_name_plural": "Instituições",},
        ),
        migrations.CreateModel(
            name="InstitutionCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "campus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution_campus",
                        to="core.Campus",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution_campus",
                        to="core.Institution",
                        verbose_name="instituição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição - Campus",
                "verbose_name_plural": "Instituições do Campus",
                "unique_together": {("institution", "campus")},
            },
        ),
        migrations.AddField(
            model_name="campus",
            name="institutions",
            field=models.ManyToManyField(
                related_name="campus",
                through="core.InstitutionCampus",
                to="core.Institution",
                verbose_name="instituições",
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campus",
                to="core.Location",
                verbose_name="localização",
            ),
        ),
        migrations.AddField(
            model_name="academiceducationcampus",
            name="campus",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="course_campus", to="core.Campus"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academiceducationcampus", unique_together={("campus", "academic_education")},
        ),
    ]
