# Generated by Django 3.0.5 on 2020-05-14 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add__academic_education__course__grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEducationCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "academic_education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_campus",
                        to="core.AcademicEducation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "academic_education",
                    models.ManyToManyField(
                        related_name="campus", through="core.AcademicEducationCampus", to="core.AcademicEducation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institution_campus",
                        to="core.Campus",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institution_campus",
                        to="core.Institution",
                    ),
                ),
            ],
            options={"unique_together": {("institution", "campus")},},
        ),
        migrations.AddField(
            model_name="campus",
            name="institutions",
            field=models.ManyToManyField(
                related_name="campus", through="core.InstitutionCampus", to="core.Institution"
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campus", to="core.Location"
            ),
        ),
        migrations.AddField(
            model_name="academiceducationcampus",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="course_campus", to="core.Campus"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academiceducationcampus", unique_together={("campus", "academic_education")},
        ),
    ]
