# Generated by Django 3.0.5 on 2020-05-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add__course__grade__academic_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEducationInstitutionCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "academic_education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions_campus",
                        related_query_name="institution_campus",
                        to="core.AcademicEducation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True,),),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True,),),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="InstitutionCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions_campus",
                        related_query_name="institution_campus",
                        to="core.Campus",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions_campus",
                        related_query_name="institution_campus",
                        to="core.Institution",
                    ),
                ),
            ],
            options={"unique_together": {("institution", "campus")},},
        ),
        migrations.AddField(
            model_name="campus",
            name="institutions",
            field=models.ManyToManyField(
                related_name="campus", through="core.InstitutionCampus", to="core.Institution"
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campus", to="core.Location"
            ),
        ),
        migrations.AddField(
            model_name="AcademicEducationInstitutionCampus",
            name="institution_campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_education",
                to="core.InstitutionCampus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="AcademicEducationInstitutionCampus", unique_together={("institution_campus", "academic_education")},
        ),
    ]
