# Generated by Django 3.0.5 on 2020-05-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add__institution__campus"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEducation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="AcademicEducationCampus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "academic_education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_education_campus",
                        to="core.AcademicEducation",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_education_campus",
                        to="core.Campus",
                    ),
                ),
            ],
            options={"unique_together": {("academic_education", "campus")},},
        ),
        migrations.AddField(
            model_name="academiceducation",
            name="campi",
            field=models.ManyToManyField(
                related_name="academic_education", through="core.AcademicEducationCampus", to="core.Campus"
            ),
        ),
        migrations.AddField(
            model_name="academiceducation",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="academic_education", to="core.Grade"
            ),
        ),
    ]
