# Generated by Django 3.0.5 on 2020-05-06 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_institution_campus_institutionCampus_academicEducationCampus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z A-Z]*$", message="Este campo deve conter somente letras"
                            )
                        ],
                        verbose_name="nome",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z A-Z]*$", message="Este campo deve conter somente letras"
                            )
                        ],
                        verbose_name="sobrenome",
                    ),
                ),
                ("cpf", models.CharField(help_text="Somente números", max_length=11, unique=True)),
                (
                    "rg",
                    models.CharField(
                        help_text="Somente números",
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$", message="Este campo deve conter somente números"
                            )
                        ],
                    ),
                ),
                ("born_date", models.DateField(verbose_name="data de nascimento")),
                ("gender", models.CharField(choices=[("F", "Feminino"), ("M", "Masculino")], max_length=1)),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="DDD + número",
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$", message="Este campo deve conter somente números"
                            )
                        ],
                        verbose_name="contato",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="atualizado em")),
            ],
            options={"verbose_name": "Pessoa", "verbose_name_plural": "Pessoas",},
        ),
    ]
