# Generated by Django 3.0.6 on 2020-06-24 20:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add__person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsible",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibles",
                        related_query_name="responsible",
                        to="core.Person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("_academic_education_campus_deleted_id", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "registration",
                    models.CharField(
                        max_length=35,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$", message="Este campo deve conter somente números"
                            )
                        ],
                    ),
                ),
                ("graduated", models.BooleanField(default=False)),
                ("ingress_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_education_campus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        related_query_name="student",
                        to="core.AcademicEducationCampus",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_registrations",
                        related_query_name="student_registration",
                        to="core.Person",
                    ),
                ),
                (
                    "responsibles_persons",
                    models.ManyToManyField(
                        related_name="dependents",
                        related_query_name="dependent",
                        through="core.Responsible",
                        to="core.Person",
                    ),
                ),
            ],
            options={"unique_together": {("person", "academic_education_campus")},},
        ),
        migrations.AddField(
            model_name="responsible",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibles",
                related_query_name="responsible",
                to="core.Student",
            ),
        ),
        migrations.AlterUniqueTogether(name="responsible", unique_together={("student", "person")},),
    ]
