# Generated by Django 3.1 on 2020-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add__student__responsible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=150)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=150)),
            ],
            options={"abstract": False,},
        ),
    ]
