# Generated by Django 5.1.1 on 2024-09-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_academiceducation_deleted_by_cascade_and_more"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="profile_image",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="O upload da imagem deve ser feito antes, para obter o atributo de associação",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
