# Generated by Django 5.1.3 on 2024-12-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="team",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.team"),
        ),
    ]
