# Generated by Django 5.1.3 on 2024-12-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_student_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.team"),
        ),
    ]
